### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [Siddley/Creole#1]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by pchaigno** [comment]
@Siddley Did you get a chance to look into this?

**Comment by Siddley** [comment]
Hi, no problem, which license would you prefer?

**Comment by pchaigno** [comment]
People usually prefer MIT for its simplicity, but any permissive license is fine really :-)

**Comment by Siddley** [comment]
Ok, changes done :-) Enjoy!

**Comment by arfon** [comment]
Thanks @Siddley. This is merged into Linguist now and will be live on GitHub next week: https://github.com/github/linguist/pull/2999
